<script setup lang="ts">
import {
  Search,
  MapPin,
  UserRound,
  Heart,
  ShoppingBag,
  Menu,
  X,
  ArrowUpRight,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Minus,
  Check,
  SlidersHorizontal,
  Footprints,
  Cloud,
  Feather,
  ShieldCheck,
  Home,
  Grid2X2,
  Truck,
  RotateCcw,
  Instagram,
  Facebook,
  MoveUp,
  MoveDown,
  Navigation,
  Mail,
  Trash2,
  Sun,
  Star,
  Play,
  Pause,
} from 'lucide-vue-next'
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 22 })
const icons: Record<string, any> = {
  search: Search,
  pin: MapPin,
  user: UserRound,
  heart: Heart,
  bag: ShoppingBag,
  menu: Menu,
  close: X,
  upRight: ArrowUpRight,
  arrow: ArrowRight,
  left: ArrowLeft,
  down: ChevronDown,
  right: ChevronRight,
  prev: ChevronLeft,
  plus: Plus,
  minus: Minus,
  check: Check,
  filter: SlidersHorizontal,
  footprints: Footprints,
  cloud: Cloud,
  feather: Feather,
  shield: ShieldCheck,
  home: Home,
  grid: Grid2X2,
  truck: Truck,
  returns: RotateCcw,
  instagram: Instagram,
  facebook: Facebook,
  up: MoveUp,
  moveDown: MoveDown,
  location: Navigation,
  mail: Mail,
  trash: Trash2,
  sun: Sun,
  star: Star,
  play: Play,
  pause: Pause,
}
</script>
<template>
  <component
    :is="icons[props.name] || ArrowRight"
    :size="size"
    :stroke-width="1.6"
    aria-hidden="true"
  />
</template>
